# Generated by Django 5.0.1 on 2024-01-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="preco_marketing",
            field=models.FloatField(verbose_name="Preço"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_marketing_promocional",
            field=models.FloatField(default=0, verbose_name="Preço Promocional"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo",
            field=models.CharField(
                choices=[("V", "Variavel"), ("S", "Simples")], default="V", max_length=1
            ),
        ),
    ]
