# Generated by Django 5.0.1 on 2024-01-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0002_alter_produto_preco_marketing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
