# Generated by Django 5.0.1 on 2024-01-08 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Aprovado"),
                            ("C", "Criado"),
                            ("R", "Reprovado"),
                            ("P", "Pendente"),
                            ("E", "Enviado"),
                            ("F", "Finalizado"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto_nome", models.CharField(max_length=100)),
                ("produto_id", models.PositiveIntegerField()),
                ("variacao_nome", models.CharField(max_length=100)),
                ("variacao_id", models.PositiveIntegerField()),
                ("preco", models.FloatField()),
                ("preco_promocional", models.FloatField(default=0)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("imagem", models.CharField(max_length=1000)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pedido.pedido"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Items do Pedido",
            },
        ),
    ]
